### ISSUE TITLE
[FEATURE] 多wan拨号和AppImage

### ISSUE THREAD

**Issue by GuangYu-yu** [ThisSeanZhang/landscape#29]
### 背景说明 / Background
不能多wan拨号，使用docker没有AppImage

### 提议方案 / Proposal

**详细描述** / Detailed Description：
多wan负载均衡不知道可不可以这样，我对这方面不太了解。此外AppImage比docker使用更加便捷，如果能在路由器web中使用AppImage就好了。

```
policies:
  - name: 移动  # 策略名称
    interface-name: 
      type: direct
      use:
        pppoe-cmcc  # 接口名称
    use-rules:
      - 规则1
      - 规则2
    dns:  # 可选：dns服务器
      servers:
        - dns1
        - dns2
      dnsmod: 最快IP # 可选：最快IP 最快Ping 最快响应
    health-check:
      url: https://www.qq.com/favicon.ico  # 健康检查地址
      interval: 300  # 健康检查间隔
      timeout: 5000  # 健康检查超时
    metric: # 跃点数
    weight: # 权重

  - name: 联通  # 策略名称
    interface-name: 
      type: direct
      use:
        pppoe-cnc  # 接口名称
    use-rules:
      - 规则1
      - 规则2
    dns:  # 可选：dns服务器
      servers:
        - dns1
        - dns2
      dnsmod: 最快IP # 可选：最快IP 最快Ping 最快响应
    health-check:
      url: https://www.qq.com/favicon.ico  # 健康检查地址
      interval: 300  # 健康检查间隔
      timeout: 5000  # 健康检查超时
    metric: # 跃点数
    weight: # 权重

  - name: 电信  # 策略名称
    interface-name: 
      type: direct
      use:
        pppoe-ct  # 接口名称
    use-rules:
      - 规则1
      - 规则2
    dns:  # 可选：dns服务器
      servers:
        - dns1
        - dns2
      dnsmod: 最快IP # 可选：最快IP 最快Ping 最快响应
    health-check:
      url: https://www.qq.com/favicon.ico  # 健康检查地址
      interval: 300  # 健康检查间隔
      timeout: 5000  # 健康检查超时
    metric: # 跃点数
    weight: # 权重
  - name: 其他  # 策略名称
    interface-name: 
      type: # 可选：direct round-robin consistent-hashing sticky-sessions
      use:
        - pppoe-cmcc  # 接口名称
        - pppoe-cnc  # 接口名称
        - pppoe-ct  # 接口名称
    use-rules:
      - 规则1
      - 规则2
    dns:  # 可选：dns服务器
      servers:
        - dns1
        - dns2
      dnsmod: 最快IP # 可选：最快IP 最快Ping 最快响应
    health-check:
      url: https://www.qq.com/favicon.ico  # 健康检查地址
      interval: 300  # 健康检查间隔
      timeout: 5000  # 健康检查超时
    metric: # 跃点数
    weight: # 权重

rules:
  - name: 规则1
    url: 
    interval: 86400
  - name: 规则2
    url:
    interval: 86400

dns:
  - name: dns1
    ip-address: 
    port: 
    type: # 可选：UDP TCP DOH DOT DOQ Http
  - name: dns2
    ip-address:
    port:
    type: 
```

### 用户场景 / User Story
作为小白
我需要多wan拨号 AppImage在web使用

### 技术影响 / Technical Impact
- [ ] 需要新依赖 / Requires new dependencies
- [ ] 影响现有API / Affects existing APIs
- [ ] 需要数据迁移 / Needs data migration
